In [5]:
from collections import namedtuple
Rec=namedtuple('Rec','x y')
r=Rec(2,3)
print(r)

Rec(x=2, y=3)

In [12]:
from collections import deque
q=deque([1,2,3,4])
q.append(1)
q.pop()
q.appendleft(5)
q
q.pop()

4

In [13]:
from collections import Counter
nums=[1,2,3,1,4,5,6,3,2,7,8,4,5,6,3]
c=Counter(nums)
print(c)

Counter({3: 3, 1: 2, 2: 2, 4: 2, 5: 2, 6: 2, 7: 1, 8: 1})

In [21]:
nums=[10,20,30]
n=iter(nums)
while True:
    try:
        print(next(n))
    except Exception as e:
        print(type(e))
        break

10
20
30
<class 'StopIteration'>

In [29]:
def func(n):
    for i in range(n):
        yield i*i
a=func(1000000)
for i,value in enumerate(a):
    if i>10:
        break
    print(value)

0
1
4
9
16
25
36
49
64
81
100

In [32]:
def deco(func):
    def wrapper(*args,**kwargs):
        print("Start")
        res=func(*args,**kwargs)
        print(res)
        print("End")
        
    return wrapper
@deco
def add(a,b):
    return a+b

@deco
def subtract(a,b):
    return b-a
add(2,3)
subtract(2,3)

Start
5
End
Start
1
End

In [33]:
import logging
logging.basicConfig(level=logging.WARN,format='%(asctime)s-%(name)s-%(levelname)s-%(message)s',filename="a.log",filemode="a")
logger=logging.getLogger(__name__)
class Bankaccount:
    def __init__(self,balance=0):
        self.__balance=balance
    def __str__(self):
        return f"{self.__balance}"
    def deposit(self, amt):
        if amt <= 0:
            logger.warning("Deposit amount must be positive")
        else:
            self.__balance += amt
            logger.warning(f"Deposited {amt}. New balance: {self.__balance}")
    def withdraw(self, amt):
        if amt > self.__balance:
            logger.warning("Insufficient balance")
        else:
            self.__balance -= amt
            logger.warning(f"Withdrew {amt}. New balance: {self.__balance}")

B=Bankaccount(1000)
B.deposit(100)
print(B)
B.withdraw(1000)
print(B)

1100
100

In [35]:
class Animal:
    def __init__(self,name):
        self.name=name
    def __str__(self):
        return f"The name of the dog is {self.name}"
class Dog(Animal):
    def __init__(self,name,breed):
        super().__init__(name)
        self.breed=breed
    def __str__(self):
        return f"{super().__str__()}\nThe breed is {self.breed}"

d=Dog("hh","heroic")
print(d)

The name of the dog is hh
The breed is heroic

In [39]:
import pdb
x=[1,2,3]
pdb.set_trace()
y=x[2]
y=x[4]

None
> /tmp/ipykernel_4396/1460631311.py(3)<module>()
      1 import pdb
      2 x=[1,2,3]
----> 3 pdb.set_trace()
      4 y=x[2]
      5 y=x[4]

      1 import pdb
      2 x=[1,2,3]
----> 3 pdb.set_trace()
      4 y=x[2]
      5 y=x[4]

IndexError: list index out of range

chapter 2

In [49]:
data="Hello world"
with open("a.txt","a") as f:
    f.write(data)

In [65]:

with open("b.txt","a") as f:
    f.write("Hello workld \n i am don of this world")

In [61]:
with open("a.txt","r") as f:
    content=f.read()
    print(content)

Hello worldHello worldHello world

In [62]:
with open("b.txt","r") as f:
    content=f.readlines()
    print(content)

['Hello world\n', ' Neoal               Hello world\n', ' Neoal               ']

In [63]:
with open("b.txt","r") as f:
    content=f.readline()
    print(content)

Hello world

In [77]:
import csv,json
data=[['Name','Age'],['A',23]]
with open("m.csv",'w',newline="") as f:
    w=csv.writer(f)
    print(type(w))
    w.writerows(data)

<class '_csv.writer'>

In [76]:
import pandas as pd
data=pd.DataFrame([
    {'Roll_no':1,'Name':'Ram'},
    {'Roll_no':2,'Name':'sita'}
])
data.to_csv("MMM.csv",index=False)

In [74]:
import pandas as pd
df=pd.read_csv("m.csv")
df["City"]='AYuhs'  
df.to_csv("ss.csv",index=False)
df

  Name  Age   City
0    A   23  AYuhs

In [79]:
data=([
    {'Roll_no':1,'Name':'Ram'},
    {'Roll_no':2,'Name':'sita'}
])
with open("writer.csv",'a') as f:
    writer=csv.DictWriter(f,fieldnames=["Roll_no","Name"])
    writer.writeheader()
    writer.writerows(data)

In [82]:
import json
data=([
    {'Roll_no':1,'Name':'Ram',"courses":["c++",'pyhton']},
    {'Roll_no':2,'Name':'sita',"courses":['c','data science']}
])
with open("jsossn.json",'a') as f:
    json.dump(data,f,indent=4)

In [84]:
import json
with open('jsossn.json','r') as f:
    data=json.load(f)
    print(data)

[{'Roll_no': 1, 'Name': 'Ram', 'courses': ['c++', 'pyhton']}, {'Roll_no': 2, 'Name': 'sita', 'courses': ['c', 'data science']}]

In [85]:
data=pd.DataFrame([
    {'Roll_no':1,'Name':'Ram',"courses":["c++",'pyhton']},
    {'Roll_no':2,'Name':'sita',"courses":['c','data science']}
])
data.to_excel("Emp.xlsx",sheet_name="roo",engine="openpyxl",index=False)

In [88]:
f=pd.read_excel("Emp.xlsx")
f.head()

   Roll_no  Name                courses
0        1   Ram      ['c++', 'pyhton']
1        2  sita  ['c', 'data science']

In [96]:
import sqlite3

conn = sqlite3.connect("example.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS students(
    id INTEGER PRIMARY KEY,
    name TEXT
)
""")

cursor.execute("""
INSERT OR IGNORE INTO students VALUES(1, "Ayush")
""")

conn.commit()   # 🔥 important

cursor.execute("SELECT id, name FROM students")
rows = cursor.fetchall()   # 🔥 important

print(rows)

[(1, 'Ayush')]

In [99]:
conn=sqlite3.connect("example.db")
cursor=conn.cursor()
cursor.execute("Insert or ignore into students(id,Name) values(?,?)",(2,"ram"))
conn.commit()
cursor.execute("SELECT id, name FROM students")
rows = cursor.fetchall()   # 🔥 important

print(rows)

conn.close()

[(1, 'Ayush'), (2, 'ram')]

In [ ]:
from pymongo import MongoClient